<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>EldenRingOrganizer</AssemblyName>
    <RootNamespace>EldenRingOrganizer</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hexa.NET.GLFW" Version="1.0.4" />
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Backends.GLFW" Version="1.0.18" />
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.22.0" />
    <PackageReference Include="Silk.NET.DXGI" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\Smithbox\src\Smithbox.Program\Smithbox.Program.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\external\Smithbox\src\Smithbox.Data\Assets\PARAM\ER\**\*"
             Link="Assets\PARAM\ER\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\external\Smithbox\src\Smithbox.Data\Assets\Localization\**\*"
             Link="Assets\Localization\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\..\external\Smithbox\LICENSE"
             Link="Licenses\Smithbox-LICENSE.txt"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
